version: "3.9"  # optional since v1.27.0
services:
  api:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    image: ais_ml_server:v1
    volumes:
      - ..:/app
      - /dev/shm:/dev/shm
    environment:
      - TZ=Asia/Kuala_Lumpur
    container_name: api_gateway
    network_mode: host
    restart: always
  
  mongodb:
    image: mongo:4.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: edwin
      MONGO_INITDB_ROOT_PASSWORD: cheong-25
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro